# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.2
_src_path: gh:algorandfoundation/algokit-beaker-default-template
algod_port: 4001
algod_server: http://localhost
algod_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
author_email: thedorsan@protonmail.com
author_name: D0rs4n
contract_name: fractdistribution
deployment_language: python
ide_vscode: true
indexer_port: 8980
indexer_server: http://localhost
indexer_token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
preset_name: production
project_name: fractic-contracts
python_linter: flake8
use_dispenser: true
use_github_actions: true
use_pre_commit: true
use_python_black: true
use_python_mypy: false
use_python_pip_audit: true
use_python_pytest: true
